"""Fix back_populate issues between tables

Revision ID: 0e44b7a5dbb2
Revises: c1a5f307f074
Create Date: 2023-04-29 11:01:29.072665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e44b7a5dbb2'
down_revision = 'c1a5f307f074'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
