"""Add unique constraint to 'title' in 'category' table

Revision ID: 1668740c3978
Revises: 80a7a4e20867
Create Date: 2023-05-06 13:18:38.614909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1668740c3978'
down_revision = '80a7a4e20867'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Original version:
    # op.create_unique_constraint('uq_category_title', 'transaction_category', ['title'])

    #Updated version:
    op.execute("CREATE UNIQUE INDEX uq_category_title ON transaction_category (title)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Original version:
    # op.drop_constraint('uq_category_title', 'transaction_category', type_='unique')

    op.execute("DROP INDEX uq_category_title")
    # ### end Alembic commands ###
